package com.example.cropdoctorai.data.remote

/**
 * Holds the structured analysis response from Gemini AI.
 * All fields are dynamically generated by Gemini based on the actual
 * crop prediction — nothing is hardcoded.
 *
 * @param aboutDisease A detailed paragraph explaining the detected condition
 * @param organicRemedies List of organic/biological treatment recommendations
 * @param chemicalRemedies List of chemical/agrochemical treatment recommendations
 * @param preventionTips List of proactive prevention measures
 */
data class GeminiAnalysis(
    val aboutDisease: String,
    val organicRemedies: List<String>,
    val chemicalRemedies: List<String>,
    val preventionTips: List<String>
)
